#!/usr/bin/env python
"""main.py - auto-generated by softnanotools"""
import starpolymers

from softnanotools.logger import Logger
logger = Logger('GENERATE')

def main(**kwargs):
    logger.info('Running main...')
    lammps_system = starpolymers.generators.System(50)
    molecule_factory = starpolymers.MoleculeFactory([
            {
                'molecule': 'hexagon',
            }
        ])
    lammps_system.add_molecules(molecule_factory.molecules)
    config_file = starpolymers.ConfigFile(lammps_system)
    config_file.write('config.dat')
    logger.info('Done!')
    return

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='main.py - auto-generated by softnanotools')
    main(**vars(parser.parse_args()))
