#!/usr/bin/env python
"""main.py - auto-generated by softnanotools"""
from softnanotools.logger import Logger
logger = Logger('MAIN')

def main(**kwargs):
    logger.info('Running main...')
    # insert code here
    logger.info('Done!')
    return

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='main.py - auto-generated by softnanotools')
    main(**vars(parser.parse_args()))

